version: '2'
services:
  proxy:
    image: quay.io/continuouspipe/nginx-reverse-proxy:stable
    links:
      - varnish
    environment:
      PROXY_LOCATIONS: '[{"location": "/", "backend": "http://varnish", "preserve_host": true}]'
      WEB_HTTPS_ONLY: true
    expose:
      - 80
      - 443

  varnish:
    image: quay.io/continuouspipe/drupal8-varnish4:stable
    links:
      - web
    environment:
      DRUPAL_CACHE_ERRORS: "false"
    expose:
      - 80

  web:
    build:
      context: .
      args:
        - GITHUB_TOKEN
    volumes:
      - .:/app
    links:
      - database
    environment:
      - DRUPAL_HASH_SALT=sosecret
      - DATABASE_NAME=drupaldb
      - DATABASE_USER=drupal
      - DATABASE_PASSWORD=drupal
      - DRUPAL_ADMIN_USERNAME=drupaluser
      - DRUPAL_ADMIN_PASSWORD=drupalpass
      - WEB_HTTPS_OFFLOADED="true"
      - WEB_HTTPS="false"
    expose:
      - 80

  database:
    image: quay.io/continuouspipe/mysql5.6:stable
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    expose:
      - 3306
